Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -15,6 +15,20 @@ pool:
     - Agent.OS -equals Linux
 
 steps:
+- script: |
+    if ! dpkg-query -W -f='${Status}' maven 2>/dev/null | grep -q "install ok installed"; then
+      echo "Maven not found. Installing Maven..."
+      sudo apt-get update
+      sudo apt-get install -y maven
+    else
+      echo "Maven is already installed."
+    fi
+  displayName: 'Check and Install Maven using dpkg if necessary'
+
+# Verify Maven installation
+- script: |
+    mvn -version
+  displayName: 'Verify Maven Installation'
 - task: Maven@3
   inputs:
     mavenPomFile: 'pom.xml'
